# Generated by Django 5.0.6 on 2024-05-21 02:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=50)),
                ('description', models.TextField()),
                ('inStock', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('stockDate', models.DateField(verbose_name=models.DateTimeField(default=datetime.datetime.now, null=True))),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products_photos/%Y/%m/%d/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
